modmap:
  - name: CapsLock as Left CTRL/Esc
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
        alone_timeout_millis: 500
  - name: Left CTRL as CTRL/Esc
    remap:
      Ctrl_L:
        held: Ctrl_L
        alone: Esc
        alone_timeout_millis: 500
  - name: Right CTRL as CTRL/Esc
    remap:
      Ctrl_R:
        held: Ctrl_R
        alone: Esc
        alone_timeout_millis: 500

  - name: Vim_Mode
    remap:
      H: LEFT
      J: DOWN
      K: UP
      L: RIGHT
    mode: Vim_Mode

keymap:
  - name: Vim Mode - Enable
    remap:
      ALT-I: { set_mode: Vim_Mode }
    mode: default
  - name: Vim Mode - Disable
    remap:
      ALT-I: { set_mode: default }
    mode: Vim_Mode
